---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook))

  - name: fauna-python-repository
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/fauna-python
      branch: main

  - name: fauna-python-repository-docs
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-python.git
      branch: gh-pages
      private_key: ((github_repo_key))

  - name: testtools-repo
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/testtools.git
      branch: main
      private_key: ((github_repo_key))

  - name: testtools-image
    type: registry-image
    icon: docker
    source:
      repository: devex-dx-drivers-platform-tests
      aws_access_key_id: ((prod-images-aws-access-key-id))
      aws_secret_access_key: ((prod-images-aws-secret-key))
      aws_region: us-east-2

groups:
  - name: standard-release
    jobs:
      - set-self
      - release

jobs:
  - name: set-self
    plan:
      - get: fauna-python-repository
        trigger: true
      - set_pipeline: self
        file: fauna-python-repository/concourse/pipeline.yml

  - name: test
    serial: true
    plan:
      - get: fauna-python-repository
        passed:
          - set-self
      - get: testtools-repo
      - get: testtools-image

      - load_var: git-commit
        reveal: true
        file: fauna-python-repository/.git/ref

      - in_parallel:
          fail_fast: false
          steps:
            - task: unit-and-integration-tests
              file: fauna-python-repository/concourse/tasks/tests.yml
              privileged: true

            - task: aws-lambda-tests
              image: testtools-image
              file: testtools-repo/fauna-driver-platform-tests/concourse/tasks/python-aws-lambda-tests.yml
              params:
                RUNTIME: python
                PLATFORM: aws-lambda
                GIT_COMMIT: ((.:git-commit))
                FAUNA_SECRET: ((drivers-platform-tests/fauna-secret))
                AWS_LAMBDA_ROLE_ARN: ((drivers-platform-tests/aws-lambda-role-arn))
                AWS_ACCESS_KEY_ID: ((drivers-platform-tests/aws-access-key-id))
                AWS_SECRET_ACCESS_KEY: ((drivers-platform-tests/aws-secret-key))

            - task: vercel-tests
              image: testtools-image
              file: testtools-repo/fauna-driver-platform-tests/concourse/tasks/python-vercel-tests.yml
              params:
                RUNTIME: python
                PLATFORM: vercel
                GIT_COMMIT: ((.:git-commit))
                FAUNA_SECRET: ((drivers-platform-tests/fauna-secret))
                VERCEL_TOKEN: ((drivers-platform-tests/vercel-token))


  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-python-repository
        passed:
          - unit-and-integration-tests
          - aws-lambda-tests
          - vercel-tests

      - get: fauna-python-repository-docs

      - task: build
        file: fauna-python-repository/concourse/tasks/build.yml

      - task: publish
        file: fauna-python-repository/concourse/tasks/publish.yml
        params:
          TWINE_USERNAME: ((pypi-username))
          TWINE_PASSWORD: ((pypi-password))
        on_success:
          put: notify
          params:
            text_file: slack-message/publish

      - task: publish-docs
        file: fauna-python-repository/concourse/tasks/publish-docs.yml

      - put: fauna-python-repository-docs
        params:
          repository: fauna-python-repository-updated-docs
