---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: shared-concourse-dind
    aws_access_key_id: ((prod-images-aws-access-key-id))
    aws_secret_access_key: ((prod-images-aws-secret-key))
    aws_region: us-east-2

inputs:
  - name: fauna-python-repository

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceu
    - |
      # start containers
      docker-compose -f fauna-python-repository/tests/docker-compose-tests.yml run python-311
      docker-compose -f fauna-python-repository/tests/docker-compose-tests.yml run python-310
      docker-compose -f fauna-python-repository/tests/docker-compose-tests.yml run python-39
      # stop and remove containers
      docker-compose -f fauna-python-repository/tests/docker-compose-tests.yml down
      # remove volumes
      docker volume rm $(docker volume ls -q)
