name: Python Driver Tests
on:
  pull_request:
    paths:
      - "**"

defaults:
  run:
    working-directory: ./

jobs:
  build_and_test:
    strategy:
      matrix:
        # Run in all these versions of Python
        # current and last three python versions
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"

    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show file descriptor limit
        run: ulimit -a

      - name: Build docker
        run: docker compose -f docker/docker-compose.yml build --build-arg BASE_IMG=python:${{ matrix.python-version }} --no-cache

      - name: Run unit tests
        run: docker compose -f docker/docker-compose.yml run --rm unit-test

      - name: Run integration tests
        run: docker compose -f docker/docker-compose.yml run --rm integration-test

      - name: Generate coverage html report with dynamic contexts
        run: docker compose -f docker/docker-compose.yml run --rm coverage

      - uses: actions/upload-artifact@v3
        with:
          name: html-code-coverage-database
          path: ./.coverage

      - uses: actions/upload-artifact@v3
        with:
          name: html-code-coverage-report
          path: ./htmlcov
